options:
  prefix: '&bOptiChat &8&l»&7 '
  aliases:
  - oc
  - chatOpti
  - oChat
chatmute:
  stats: true
  player_chatMuted:
    type: NONE
    text: ''
  player_chatUnmuted:
    type: NONE
    text: ''
  server_chatMuted:
    type: BROADCAST
    text: '&cChat has been muted!'
  server_chatUnmuted:
    type: BROADCAST
    text: '&aChat has been unmuted!'
  player_triesChat:
    type: SEND_MESSAGE
    text: '&c&lHey!&7 Chat is muted and you my not speak!'
  player_triesCommand:
    type: SEND_MESSAGE
    text: '&c&lHey!&7 Chat is muted and you my not use that command!'
  Aliases:
  - mc
  - mchat
  - chatmute
  blockedCommands:
  - me
  - say
  - msg
  - tell
  - w
  - r
  - emsg
  - er
  - etell
  - ew
  - eme
  - esay
  - broadcast
  - bc
  - ebc
  - ebroadcast
clearChat:
  blankLines: 256
  endMessage:
  - '&bChat was cleared by %p'
  Aliases:
  - occ
  - cc
  - cclear
  - chatclear
  - clearc
AntiSwear:
  words:
  - motherfucker
  - fucking
  - shiting
  - shitting
  - fuck
  - shit
  - bitch
  - nigger
  - ass
  - slut
  - dick
  - penis
  - vagina
  - pussy
  - cunt
  - dildo
  - whore
  - cum
  whitelist:
  - glass
  - pass
  - null
  actionOne:
    type: REPLACE_WORD
    text: '*****'
  actionTwo:
    type: SEND_MESSAGE
    text: '&cYou cant say that word!'
AntiCaps:
  maxCapsPercent: 25
  minLength: 4
  uppercase-characters: ABCDEFGHIJKLMNOPQRSTUVWXYZ
  actionOne:
    type: SET_LOWERCASE
    text: ''
  actionTwo:
    type: SEND_MESSAGE
    text: '&cCalm down with the CAPS there!'
AntiAD:
  actionOne:
    type: REPLACE_WORD
    text: '********'
  actionTwo:
    type: SEND_MESSAGE
    text: '&cWe do &lNOT&c tollerate advertizing!'
config: 2
